### PR TITLE
Use the permission feature of MCDR

### PR DESCRIPTION
**Pull request by MiKayule**

### CODE REVIEW

**Comment by MiKayule** [comment]
I misunderstood the original code and need to do some edit

**Comment by MiKayule** [comment]
Bug fixed and converted all tabs to spaces, please review and merge it if possible.

**Comment by Fallen-Breath** [comment]
u can simply send `info` into `get_permission_level` to get permission level btw
~~and why r u yeeting tab~~

**Comment by MiKayule** [comment]
u know PEP 8 specified it lol

**Pull request merged**
